git:
  projectToolBar-17:
    items:
    - {id: fetch}
    - {id: sync}
    - {id: push}
    - {stretching: false}
    - {id: commit}
    - {stretching: true}
    - {id: stage}
    - {id: indexEditor}
    - {id: unstage}
    - {stretching: false}
    - {id: discard}
    - {stretching: false}
    - {id: stashSave}
    - {id: stashApply}
    - {stretching: true}
    - {id: logRepository}
    - {id: annotate}
    - {id: investigate}
    - {stretching: true}
    - {id: flowContext}
    - {stretching: false}
    - {id: merge}
    - {id: rebaseHeadTo}
  logToolBar-18.2:
    items:
    - {id: fetch}
    - {id: sync}
    - {id: push}
    - {stretching: false}
    - {id: commit}
    - {stretching: true}
    - {id: stage}
    - {id: indexEditor}
    - {id: unstage}
    - {stretching: false}
    - {id: discard}
    - {stretching: false}
    - {id: stashSave}
    - {id: stashApply}
    - {stretching: true}
    - {id: annotate}
    - {id: investigate}
    - {stretching: true}
    - {id: flowContext}
    - {stretching: false}
    - {id: merge}
    - {id: rebaseHeadTo}
hg:
  projectToolBar:
    items:
    - {id: fetch}
    - {id: push}
    - {stretching: false}
    - {id: merge}
    - {id: rebaseHeadTo}
    - {id: commit}
    - {stretching: true}
    - {id: add}
    - {id: remove}
    - {stretching: false}
    - {id: discard}
    - {id: delete}
    - {stretching: false}
    - {id: stashSave}
    - {id: stashApply}
    - {stretching: true}
    - {id: log}
    - {id: annotate}
    - {stretching: true}
    - {id: windowLayoutSetMain}
    - {id: windowLayoutSetReview}
  logToolBar:
    items:
    - {id: checkout}
    - {id: branchClose}
    - {stretching: true}
    - {id: merge}
    - {id: cherryPick}
    - {id: revert}
    - {id: rebaseHeadTo}
    - {id: reset}
    - {stretching: true}
    - {id: branchAddTag}
    - {stretching: true}
    - {id: annotate}
    - {stretching: true}
    - {id: windowLayoutSetMain}
    - {id: windowLayoutSetReview}
filterConfiguration: {}
